// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw0YInbILQLcaVuL-YTQecv9FrJZr6i_o',
    appId: '1:147790097813:web:ea87bfa09e787db3079a9c',
    messagingSenderId: '147790097813',
    projectId: 'musicstreaming-84767',
    authDomain: 'musicstreaming-84767.firebaseapp.com',
    databaseURL: 'https://musicstreaming-84767-default-rtdb.firebaseio.com',
    storageBucket: 'musicstreaming-84767.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgpDDoNQLbq5kOq8RHnXggbuT84kicoms',
    appId: '1:147790097813:android:09fc2ff002ffaf6a079a9c',
    messagingSenderId: '147790097813',
    projectId: 'musicstreaming-84767',
    databaseURL: 'https://musicstreaming-84767-default-rtdb.firebaseio.com',
    storageBucket: 'musicstreaming-84767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWY4OfcabR-Us-AXLPI7DSKN6CtKZv2Q8',
    appId: '1:147790097813:ios:27af3653ae2947c6079a9c',
    messagingSenderId: '147790097813',
    projectId: 'musicstreaming-84767',
    databaseURL: 'https://musicstreaming-84767-default-rtdb.firebaseio.com',
    storageBucket: 'musicstreaming-84767.appspot.com',
    iosClientId: '147790097813-rfomfk11mmr4pa0uq0k51tirqrj7dpju.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
